### ISSUE TITLE
pH missing unit_of_measurement - no graph

### ISSUE THREAD

**Issue by msavazzi** [MikeJMcGuire/HASSAddons#106]
The pH is missing the unit_of_measurement so the graph becomes:
<img width="420" alt="image" src="https://github.com/MikeJMcGuire/HASSAddons/assets/2660032/673c2eca-2cf8-4e35-99fa-ed3894e7ba2e">

while it should be
<img width="420" alt="image" src="https://github.com/MikeJMcGuire/HASSAddons/assets/2660032/9fedea29-aa30-45af-a755-704f3e646e1e">

**Comment by MikeJMcGuire** [comment]
Yep - sorry for the delay. Added in v2023.11.0.
