### ISSUE TITLE
Add Default Precision on ph value

### ISSUE THREAD

**Issue by DeltaFox0018** [MikeJMcGuire/HASSAddons#109]
The PH sensor does not have a default precision consequently it cannot be used in automations as a trigger

<img width="558" alt="image" src="https://github.com/MikeJMcGuire/HASSAddons/assets/35847603/2842615e-30a5-4247-b4ce-0df5af0b103a">

it is possible to add default precision to the ph

I currently have a Blueriiot Blue Connect

Thank you

**Comment by MikeJMcGuire** [comment]
Yep - sorry for the delay. Added in v2023.11.0.
