### ISSUE TITLE
Portainer Business Edition: Ingress view password autofill

### ISSUE THREAD

**Issue by Morpheus8** [MikeJMcGuire/HASSAddons#132]
I have the strange behavior, that when I open the Portainer EE via the Homeassistant Ingress mode password autofill isn't working. I have tried with different browser and different PC, but I can't autofill passwords and usernames from my passwordmanager. In other situations and other addons in ingress mode I don't have this problem.

**Comment by MikeJMcGuire** [comment]
Interesting - I'm not having any issues with that in Chrome with the default password manager. Haven't tried any other browsers. Maybe its remembered not to for that site.

**Comment by Morpheus8** [comment]
I have done a few tests, it seems that it only doesn't work with my standard constellation Brave Browser and Enpass password manager. With Chrome or Firefox, however, it also works for me. Sorry for the false alarm, but thanks for your efforts.
