### ISSUE TITLE
HASS-Actron

### ISSUE THREAD

**Issue by sunnysingh-84** [MikeJMcGuire/HASSAddons#133]
Is the Hass-Actron addon still working with the latest version of home assistant 2023.03?

On a clean HA install I get the addon to install and connect but shortly after I get the following error and need to restart it to get it working again for a short period of time:

- **airconditioner.checklastupdate() no communication with actron unit (default) for at least 5 minutes. check actron connect unit can connect to the network and locate the add-on.**

The actronconnect webserver also shows the following error when addon is not working:

AConnect
Version: V0.18G
Basic Information
Connection:11X
**Error response from Server**
Connected to Wifi point `UniFi` as IP Address :192.168.1.xxx

**Comment by MikeJMcGuire** [comment]
Yep, still working. You should be able to browse to the ip address of the Ha server on port 80 and see the add-on respond. Perhaps check your networking, or other things on your HA clashing with the addon. Try turning of the power to the AC to reboot the action connect

**Comment by MikeJMcGuire** [comment]
Also, has it ever worked? The actron cloud service has been down for the last few days. People using the addon won't be affected, but if your unit is pointing to the cloud service and not HA, you'd be seeing funny behaviour.

**Comment by sunnysingh-84** [comment]
False alarm. All working after turning of the a/c breaker for a minute.

It was a test install in a new clean VM, I initially set it the addon, set static host entries in my router and it appeared to work however i found it weird that there were temp settings but then the communication issues appeared not too long after. After the power cycle a few extra sensors appeared and all looks good. Appreciate your great work!

**Comment by MikeJMcGuire** [comment]
Great to hear! Cheers.
