### ISSUE TITLE
Unable to Start - Unable to locate Unix socket or named pipe

### ISSUE THREAD

**Issue by SpencerBaker** [MikeJMcGuire/HASSAddons#140]
After installation and starting it up, I get the following error over and over until it fails to start:
```
FTL github.com/portainer/portainer/api/cmd/portainer/main.go:66 > failed validating flags | error="Unable to locate Unix socket or named pipe"
```

https://github.com/portainer/portainer/api/cmd/portainer/main.go doesn't seem to exist, but https://github.com/portainer/portainer/blob/develop/api/cmd/portainer/main.go exists.

**Comment by MikeJMcGuire** [comment]
Do you have protected mode turned off for the add-on?

**Comment by SpencerBaker** [comment]
Ah, that was it! I reinstalled it and forgot to switch that back to off.
🙏
