### ISSUE TITLE
adding the repository not working

### ISSUE THREAD

**Issue by vautieri** [MikeJMcGuire/HASSAddons#52]
I use to use the community edition of portainer, but they stopped it.  I found this and when I try to add your repository in the addins, it just doesn't add it (acts like I didn't even press the add button).  So I tried to add it via HACs, which is says your master is not organized in the proper format.  I'm running the latest release of home assistant.  I want my portio up and running again!  I'd install it manually but I have no idea how to log into homeassistant to run the docker commands etc (as when I go in through the terminal add-on, docker is an invalid command, as is sudo and other basics linux commands).

Anyways... I really hope I can get portainer working on my homeassistant again... and would love to be able to get this add-on working (but I have to be able to add the repository).  Note, i can add other repositories (such as esphome/beta etc)

**Comment by MikeJMcGuire** [comment]
Howdy, nope - definitely still works. Are you adding https://github.com/MikeJMcGuire/HASSAddons to the repositories from the add-on page on the supervisor?

**Comment by vautieri** [comment]
Thanks.  I tried it again after you closed it and it worked.  No idea
why it didn't work hours earlier, but maybe  home assistant had to be
rebooted.. as I believe a new update come in today...

**Comment by MikeJMcGuire** [comment]
Excellent. Yeah strange one. The repository.json file hasn't changed since it went in. Glad it's working now though - completely appreciate your pain regarding portainer.
