### ISSUE TITLE
Add option to disable SSL certificate verification (equals to -k in curl)

### ISSUE THREAD

**Issue by frlu94** [MikeJMcGuire/HASSAddons#77]
Hi,

I've been loving this add-on and it's great! 

But it seems the guy who is maintaining the que site really needs some modern app monitoring tools.

Their Cert has expired this weekend and my phone app/this add-on were not working due to their neglectance.

![image](https://user-images.githubusercontent.com/86481309/167282027-d845f965-a065-41aa-9155-4e5bdef35113.png)

God knows how long it will take for them to fix this.

Can we add an option to disable SSL cert verification just in case?

Thanks heaps

**Comment by frlu94** [comment]
`08-05-2022 14:39:53.98 Que.GenerateBearerToken() [0x0000004E] Base: https://que.actronair.com.au/api/v0/oauth/token
08-05-2022 14:39:54.07 Que.GenerateBearerToken() [0x0000004E] Error (System.Security.Authentication.AuthenticationException): Unable to process API HTTP response. The remote certificate is invalid because of errors in the certificate chain: NotTimeValid`

**Comment by MikeJMcGuire** [comment]
Yep - will add a config option to allow you to choose to not require certificate trust. I'm not sure that will fix the issue though, as the wall controller will probably have stopped trusting the cloud service also.
