### ISSUE TITLE
Integration to Home Assistant Core

### ISSUE THREAD

**Issue by EddieKnight1** [MikeJMcGuire/HASSAddons#82]
Hi!

I just got a Blue Connect + for my swimming pool and found your repository very quickly. Howevr I've found it cannot be added to HASS unless I use the HASS + Container version. I'm using Home Assistant Core, hence I don't have a container area to install this.

How can I install this manually in a VM?

**Comment by MikeJMcGuire** [comment]
Howdy - if you're not using HASS + Container, https://github.com/LordMike/MBW.BlueRiiot2MQTT would probably be a better choice. I use his libraries in the add-on anyway.
