### ISSUE TITLE
Homebridge stack

### ISSUE THREAD

**Issue by JohanHome** [MikeJMcGuire/HASSAddons#96]
I getting the following error. 

“Deployment error failed to deploy a stack:
services.homebridge Additional property network mode is not allowed”

any help or just guiding me in the right direction please.

**Comment by MikeJMcGuire** [comment]
Howdy, I’m not overly familiar with homebridge, but these are all standard containers, so will work with any container orchestration tool. It sounds like you have a setting in the stack config that homebridge doesn’t like.

**Comment by JohanHome** [comment]
Hi there, Thank you for coming back to me. It must be something i have done wrong in the script. Im attaching a screenshot. If you can please let me know what i have done wrong. Without God i'm Hopeless...With God i'm Fearless... On 24 Oct 2022, at 14:24, Mike J McGuire ***@***.***> wrote:﻿
Howdy, I’m not overly familiar with homebridge, but these are all standard containers, so will work with any container orchestration tool. It sounds like you have a setting in the stack config that homebridge doesn’t like.

**Comment by MikeJMcGuire** [comment]
Howdy - the image doesn't come through when you reply to the thread via email. Upload it to something like pastebin and drop the link in here (https://pastebin.com/).
